image:
  file: .gitpod.Dockerfile

tasks:
  - name: WebApp
    before: pnpm install

  - name: Updater
    before: deno cache ./updater/index.ts

ports:
  - name: Updater (server)
    port: 5000
    visibility: public
    onOpen: notify

  - name: Web app
    port: 3000
    visibility: public
    onOpen: notify