name: CI

on:
  push:
    branches:    
      - 'main'

jobs:
  read-versions:
    name: Check update for appCurrent
    runs-on: ubuntu-latest

    outputs:
      latest-app-version: ${{ steps.appLatest.outputs.release }}
      current-app-version: ${{ steps.appCurrent.outputs.prop }}
      current-repo-version: ${{ steps.repoCurrent.outputs.prop }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Reading latest released version
        id: appLatest
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: tanishq-singh-2301
          repo: tauri-react-template
          excludes: prerelease, draft

      - name: Reading Current tauri-app version
        id: appCurrent
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'src-tauri/tauri.conf.json'
          prop_path: 'package.version'

      - name: Reading Current repo version
        id: repoCurrent
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'package.json'
          prop_path: 'version'

      - run: |
          echo Latest App   v${{ steps.appLatest.outputs.release }}
          echo Current App  v${{ steps.appCurrent.outputs.prop }}
          echo Current Repo v${{ steps.repoCurrent.outputs.prop }}

  CI:
    needs: read-versions
    name: CI
    if: needs.read-versions.outputs.current-app-version != needs.read-versions.outputs.latest-app-version

    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Node.js setup
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - name: Install app dependencies
        run: yarn install

      - name: Caching for rust ~cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('src-tauri/Cargo.lock') }}

      - name: Build the app and release new build
        id: tauriBuilder
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: __VERSION__
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'

  discord-new-release:
    name: Discord (With Release)
    needs: [CI, read-versions]

    runs-on: ubuntu-latest

    steps:
      - name: Update discord if job succeeded
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          notimestamp: true
          color: 0xecc5fb
          title: New version of `application` is ready! and maybe of `updater` too!!.
          description: |
            Application : `v${{ needs.read-versions.outputs.current-app-version }}`
            Repository  : `v${{ needs.read-versions.outputs.current-repo-version }}`

            Click [here](https://tauri-react-template.vercel.app) to see preview!
            Click [here](https://github.com/tanishq-singh-2301/tauri-react-template/releases/latest) to download!
            Click [here](https://tauri-react-updater.deno.dev) to see updater!

  discord-no-release:
    name: Discord (Without Release)
    needs: [read-versions]
    if: needs.read-versions.outputs.current-app-version == needs.read-versions.outputs.latest-app-version

    runs-on: ubuntu-latest

    steps:
      - name: Update discord if job succeeded
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          notimestamp: true
          color: 0xfa7070
          title: Updated `repository`!!.
          description: |
            Application : `v${{ needs.read-versions.outputs.current-app-version }}`
            Repository  : `v${{ needs.read-versions.outputs.current-repo-version }}`

            Click [here](https://tauri-react-template.vercel.app) to see preview!
            Click [here](https://github.com/tanishq-singh-2301/tauri-react-template/releases/latest) to download!
            Click [here](https://tauri-react-updater.deno.dev) to see updater!
  