name: CI

on:
  push:
    branches:    
      - 'main'

jobs:
  CI:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Node.js setup
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Reading latest release version
        id: appLatest
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: tanishq-singh-2301
          repo: tauri-react-template
          excludes: prerelease, draft

      - name: Reading Current tauri-app version
        id: appCurrent
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'src-tauri/tauri.conf.json'
          prop_path: 'package.version'

      - run: echo "Latest Release,   v${{ steps.appLatest.outputs.release }}"
      - run: echo "Current Building, v${{ steps.appCurrent.outputs.prop }}"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.0.2

      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - name: Install app dependencies and build web
        run: |
          pnpm i
          pnpm build

      - name: Build the app and release new build
        if: steps.appLatest.outputs.release != steps.appCurrent.outputs.prop
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: __VERSION__
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'