name: TEST

on:
  push:
    branches:    
      - 'test'

jobs:
  hello:
    name: Check update for appCurrent
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      # - name: Node.js setup
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '16.x'
      #     cache: 'yarn'

      # - run: yarn install --frozen-lockfile
      # - run: yarn build

      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm build